package com.zhizhen.study;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.widget.*;import android.view.*;
public class MainActivity extends Activity {
 WebView web; String origin=""; ValueCallback<Uri[]> upload;
 public void onCreate(Bundle b){super.onCreate(b); LinearLayout box=new LinearLayout(this);box.setOrientation(1); Button connect=new Button(this);connect.setText("连接在线学习服务");box.addView(connect);web=new WebView(this);box.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(box);
 web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(true);
 web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,String url){Uri u=Uri.parse(url);if(("http".equals(u.getScheme())||"https".equals(u.getScheme()))&&url.startsWith(origin+"/"))return false;if("http".equals(u.getScheme())||"https".equals(u.getScheme())){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){}}return true;}public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())Toast.makeText(MainActivity.this,"连接失败：检查服务地址和网络",Toast.LENGTH_LONG).show();}});
 web.setWebChromeClient(new WebChromeClient(){public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> c,FileChooserParams p){if(upload!=null)upload.onReceiveValue(null);upload=c;try{startActivityForResult(p.createIntent(),10);}catch(Exception e){upload.onReceiveValue(null);upload=null;}return true;}});
 connect.setOnClickListener(new View.OnClickListener(){public void onClick(View v){settings();}}); String old=getPreferences(0).getString("url","");if(old.length()>0)load(old);else settings(); }
 void load(String s){try{Uri u=Uri.parse(s);String scheme=u.getScheme();String h=u.getHost();boolean local=h!=null&&(h.startsWith("192.168.")||h.startsWith("10.")||h.matches("172\\.(1[6-9]|2[0-9]|3[01])\\..*"));if(h==null||u.getUserInfo()!=null||!"https".equals(scheme))throw new Exception();origin=scheme+"://"+u.getEncodedAuthority();getPreferences(0).edit().putString("url",s).apply();web.loadUrl(s);}catch(Exception e){Toast.makeText(this,"请输入有效的 HTTPS 服务地址",Toast.LENGTH_LONG).show();}}
 void settings(){final EditText text=new EditText(this);text.setSingleLine(false);text.setHint("https://你的学习服务域名/");text.setText(getPreferences(0).getString("url",""));new AlertDialog.Builder(this).setTitle("连接知帧学习服务").setMessage("输入管理员提供的 HTTPS 服务地址。注册或登录后，在模型设置中填写你自己的 API Key。").setView(text).setPositiveButton("连接",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){load(text.getText().toString().trim());}}).setNegativeButton("取消",null).show();}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==10&&upload!=null){upload.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(c,d));upload=null;}}
 public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
