import {compactMaterial,outputBudget} from '../cloudflare/token-budget.mjs';
import {check,field,newSession,turn,resume,exportNotes} from '../cloudflare/core.mjs';
import constants from '../cloudflare/constants.json';
let config={base_url:'https://api.openai.com/v1',model:'',api_key:''};
const nativeFetch=window.fetch.bind(window);
const dbReady=new Promise((resolve,reject)=>{const r=indexedDB.open('bili-study-personal',1);r.onupgradeneeded=()=>{r.result.createObjectStore('sessions',{keyPath:'id'});r.result.createObjectStore('items',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('浏览器无法保存数据，请允许网站存储。'));});
async function records(store){const db=await dbReady;return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function save(store,value,previous){const db=await dbReady;return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite'),s=tx.objectStore(store);let conflict=false;if(previous!==undefined){const r=s.get(value.id);r.onsuccess=()=>{if(r.result?.updated!==previous){conflict=true;tx.abort();}else s.put(value);};}else s.put(value);tx.oncomplete=()=>resolve(value);tx.onabort=tx.onerror=()=>reject(new Error(conflict?'记录已在另一页面更新，请重新打开。':'保存失败，请检查浏览器存储空间。'));});}
async function getSession(id){const s=(await records('sessions')).find(s=>s.id===id);check(s,'学习记录不存在');return s;}
async function model(instruction,material){check(config.model&&config.api_key,'请先设置模型和 API Key。');let r;try{r=await nativeFetch(config.base_url+'/chat/completions',{method:'POST',redirect:'error',signal:AbortSignal.timeout(90000),headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.api_key},body:JSON.stringify({model:config.model,max_tokens:outputBudget(material),messages:[{role:'system',content:constants.prompt+'\n'+instruction},{role:'user',content:JSON.stringify(compactMaterial(material))}]})});}catch{throw new Error('无法连接模型：服务商可能不允许浏览器跨域请求，或网络不可达。可换支持 CORS 的服务，或使用本地 Python App。');}check(r.ok,'模型服务返回 HTTP '+r.status);try{const result=await r.json();return JSON.parse(result.choices[0].message.content.trim().replace(/^```(?:json)?\s*|\s*```$/g,''));}catch{throw new Error('模型未返回有效 JSON，进度未修改。');}}
async function pdfExtract(data){const {getDocument,GlobalWorkerOptions}=await import('./pdf.mjs');GlobalWorkerOptions.workerSrc=new URL('./pdf.worker.mjs',document.baseURI).href;const raw=atob(data.file);check(raw.length<=8000000,'文件超过 8 MB');const task=getDocument({data:Uint8Array.from(raw,c=>c.charCodeAt(0)),isEvalSupported:false,cMapUrl:new URL('./cmaps/',document.baseURI).href,cMapPacked:true,standardFontDataUrl:new URL('./standard_fonts/',document.baseURI).href,wasmUrl:new URL('./wasm/',document.baseURI).href});let doc;try{doc=await task.promise;check(doc.numPages<=150,'请拆分为 150 页以内');const pages=[];let count=0;for(let page=1;page<=doc.numPages;page++){const p=await doc.getPage(page),content=await p.getTextContent();const text=content.items.map(i=>(i.str||'')+(i.hasEOL?'\n':' ')).join('');count+=text.length;check(count<=55000,'文本超过 55,000 字符');pages.push({page,text});p.cleanup();}check(pages.some(p=>p.text.trim()),'未找到文字层，扫描件需先 OCR');return {pages,empty_pages:pages.filter(p=>!p.text.trim()).map(p=>p.page)};}finally{await task.destroy();}}
async function route(path,data){const u=new URL(path,location.origin);path=u.pathname;
 if(path==='/api/auth/me')return {multi_user:false,user:null,providers:[],runtime:'pages-personal'};
 if(path==='/api/config'){if(data){const base=new URL(data.base_url);check(base.protocol==='https:'&&!base.username&&!base.password&&!base.search&&!base.hash,'请填写有效的 HTTPS 模型服务地址');const model=field(data,'model',200),base_url=base.href.replace(/\/+$/,'');config={base_url,model,api_key:data.clear_key?'':data.api_key||(base_url===config.base_url?config.api_key:'')};}return {base_url:config.base_url,model:config.model,has_key:!!config.api_key};}
 if(path==='/api/import')throw new Error('GitHub Pages 无法代理 B 站字幕接口。请在 B 站获取字幕后导入 TXT / SRT / VTT / JSON，或使用本地 App 读取。');
 if(path==='/api/sessions')return (await records('sessions')).sort((a,b)=>b.updated-a.updated).map(s=>({id:s.id,title:s.title,updated:s.updated,demo:s.demo,ended:s.ended,count:s.plan.points.length}));
 if(path==='/api/session')return getSession(u.searchParams.get('id'));
 if(path==='/api/export')return {markdown:exportNotes(await getSession(u.searchParams.get('id')))};
 if(path==='/api/start'){const s=await newSession(data,model,constants);s.updated=Date.now()/1000;return save('sessions',s);}
 if(path==='/api/turn'||path==='/api/resume'){const s=await getSession(data.id);check(s.updated===data.version,'进度已更新，请重新打开');const previous=s.updated;const next=path.endsWith('/resume')?resume(s):await turn(s,data,model,constants.turnInstruction);next.updated=Math.max(Date.now()/1000,previous+0.001);return save('sessions',next,previous);}
 if(path==='/api/workspace/list')return (await records('items')).filter(r=>r.kind===data.kind).sort((a,b)=>b.updated-a.updated);
 if(path==='/api/workspace/save'){check(['material','task'].includes(data.kind),'资料类型无效');const item={id:data.id||crypto.randomUUID(),kind:data.kind,title:field(data,'title',200),content:String(data.content||''),done:data.done===true,due:String(data.due||'').slice(0,10),updated:Date.now()/1000};check(item.content.length<=55000,'资料过长');return save('items',item);}
 if(path==='/api/pdf/extract')return pdfExtract(data);
 if(path==='/api/pdf/review'){const pages=data.pages;check(Array.isArray(pages)&&pages.length&&pages.length<=150,'请先导入 PDF');check(pages.reduce((n,p)=>n+p.text.length,0)<=55000,'文本过长');const r=await model('校对文字，仅输出 JSON {"summary":"概述","issues":[{"page":1,"quote":"逐字原文","suggestion":"建议","reason":"理由"}]}，不判断版式，事实疑点标记待核实。',{pages});const summary=field(r,'summary');check(Array.isArray(r.issues)&&r.issues.length<=100,'校对格式无效');for(const i of r.issues){check(pages.some(p=>p.page===i.page&&p.text.includes(field(i,'quote'))),'引用无法在原页找到');field(i,'suggestion');field(i,'reason');}return {summary,issues:r.issues};}
 throw new Error('不支持的操作');
}
window.fetch=async(input,init={})=>{if(typeof input!=='string'||!input.startsWith('/api/'))return nativeFetch(input,init);try{return Response.json(await route(input,init.body?JSON.parse(init.body):undefined));}catch(e){return Response.json({error:e.message},{status:400});}};
// Fail visibly if browser storage is unavailable rather than hiding initialization errors.
dbReady.catch(()=>{});
